name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: Economistician/eb-integration/.github/workflows/pr-gate.yml@main
    with:
      python-version: "3.13"
      os: '["ubuntu-latest", "windows-latest"]'
      python_versions: '["3.11", "3.12", "3.13"]'
      run_precommit: true
      enable_typecheck: true