name: Release to PyPI

on:
  push:
    tags:
      - "v*"  # Trigger the release on version tags
  workflow_dispatch:  # Allow manual triggering

jobs:
  release:
    uses: Economistician/eb-integration/.github/workflows/pypi-release.yml@main
    with:
      python-version: "3.12"
      build-command: "python -m build --sdist --wheel"